### ISSUE TITLE
nsport and netsurf build and install without issue, but netsurf (native) doesn't run.

### ISSUE THREAD

**Issue by chlomacg** [netsurf-plan9/netsurf#2]
Netsurf framebuffer runs fine after install (I followed the nsport instructions), but netsurf native gives the error `draw: eof on event pipe: '/lib/font/bit/vga/vga.0000-007F.1' does not exist`. I checked, and it was right, so I thought a simple solution to try would be just copying vga.0000-007F.0 to vga.0000-007F.1, at which point it gave the same error but with vga.0000-007F.2, I kept doing this until vga.0000-007F.5, then it gave the new error `draw: eof on event pipe: '/sys/lib/netsurf/fonts/default.ico' does not exist`.

At this point I decided I should probably stop trying any more of my "solutions" and ask the #cat-v irc, and Ori said the font thing is likely a red herring, and that it's probably having trouble connecting to draw.

More info: This is in a VM in VMWare, running amd64 9front. I tried updating the system and building+installing again, but no dice. `sysinfo -p` returns http://sysinfo.9front.org/src/338/body

**Comment by telephil9** [comment]
Late answer as I don't usually check github. You are better off with sending me an email.
Anyway, this issue looks like an issue I had with a wrong libplumb.
Can you make sure your sysupdate ended properly and try this again ?
